### ISSUE TITLE
Single CSV tooltip not working

### ISSUE THREAD

**Issue by joewdavies** [eurostat/gridviz#113]
Tooltip not working for single CSV file datasets

See https://eurostat.github.io/gridviz/examples/test/single_csv_bugs.html

**Comment by joewdavies** [comment]
The culprit: 
`getCellFromPosition()` being called from `getCellFocusInfo()` is returning `undefined`

**Comment by jgaffuri** [comment]
I also observed a similar bug for several cases, when the resolution has special values. It seems to be indeed bacause of the line you point out.

**Comment by jgaffuri** [comment]
I think there might be something wrong with the coordinates.

In TMAX_ranking.csv:

x,y,value
5562500,4804200,1
6687500,854200,4
6712500,904200,5
6662500,904200,2
...

Since the grid resolution is 25km, we should expect the grid coordinate values to be multiples of 25000.

If this cannot be changed, they might be corrected on-the-fly with a:

```
preprocess: (c) => {
   c.x = Math.ceil(c.x/25000)*25000
   c.y = Math.ceil(c.y/25000)*25000
}
```

See https://eurostat.github.io/gridviz/docs/reference#data-pre-processing-and-filtering

**Comment by joewdavies** [comment]
In that case I will close this issue as I assume grid coordinates should always be multiples of their resolution!

**Comment by jgaffuri** [comment]
Maybe it should be included in the doc...

**Comment by jgaffuri** [comment]
I did some changes to the method `DatasetComponent.getCellFromPosition`. It should work now without the `preprocess` workaround.
