### ISSUE TITLE
WMS Tiles load faster without maxZoom

### ISSUE THREAD

**Issue by wahlatlas** [eurostat/gridviz#85]
Hope I don't imagine it but initialy I found WMS tiles to load after a significant pause compared to QGis from the same tile server. However while experimenting with the `maxZoom` setting in `.addBackgroundLayerWMS({` leaving out the `maxZoom` statement resulted in faster loading and a better initial experience (tests on retina displays):

**before** (maxZoom: 50) 
![withmaxzoom](https://github.com/eurostat/gridviz/assets/4449821/b7770157-a1e7-4380-a2b4-fa0eec1696ee)

**after** (//maxZoom)
![without maxzoom](https://github.com/eurostat/gridviz/assets/4449821/570cd744-9e05-4c52-a615-7a9179502411)

**Comment by jgaffuri** [comment]
I did some tests based on the example page here: https://eurostat.github.io/gridviz/examples/background_WMS.html

It takes ~700ms to fetch the map from gridviz.

I obtain a similar time when hitting the URL directly from https://sgx.geodatenzentrum.de/wms_basemapde?&service=WMS&request=GetMap&layers=de_basemapde_web_raster_grau&styles=&format=image%2Fjpeg&transparent=false&version=1.1.1&srs=EPSG%3A3035&width=1920&height=680&bbox=4150656,2922904,4246656,2956904

I did not observe loading time differences when deactivating the maxZoom parameter.

Could you provide maybe additional info so that I can reproduce the issue ?

**Comment by wahlatlas** [comment]
Sorry, this must have been a combination of caching and superstition, I was too fast to file an issue that is not warranted. Please close the issue.
